export const itemsArray = [
    'Overview',
    'StarGate',
    'Spacegate',
    'Stargate Step-By-Step',
    'Tutorial',
    'Iris',
    'Rover',
    'Spectre',
    'Mission-Control',
    'Chevron',
    'Chevron Client Example',
    'Postman Collection for Chevron-API',
    'Horizon',
    'CloudWalker',
    'Heartbeat',
    'Raccoon Monitoring',
    'Drax Tracing',
    'Maverick',
    'Orion',
    'GitLab',
    'Sample Code',
    'External Partner',
    'Documentation',
];

export const tableOfContents = [
    'Table of Contents',
    'Before you begin',
    'What is Chevron?',
    'Details',
    'Example scenario',
    'Where to start?',
    'Working with the API',
    'Get all permissions for an application',
    'Get permissions that match specific roles',
    'Get permissions that match specific roles and resources',
    'Get permissions for an identity token',
    'Checking permissions',
    'Configuring permissions',
    'Configuring permissions via Rover',
    'Viewing permissions in MissionControl',
    'Integrate your application with Chevron',
    'Available Iris-Broker instances',
    'Appendix 1 - Playground environment credentials',
    'Appendix 2 - Chevron Client',
];
